#!/usr/bin/python3

import sys

import Adafruit_DHT
import time, RPi.GPIO as GPIO
import http.client as http
import urllib
import json
deviceId = "DvNQPIBk"
deviceKey = "0aRa0DILqefF4EXO"

# Parse command line parameters.

GPIO.setmode(GPIO.BCM)
GPIO.setup(17,GPIO.OUT)

def post_to_mcs(payload):
        headers = {"deviceKey": deviceKey}
        not_connected = 1
        while (not_connected):
                try:
                        conn = http.HTTPConnection("api.mediatek.com:80")
                        conn.connect()
                        not_connected = 0
                except (http.HTTPException, socket.error) as ex:
                        print ("Error: %s" % ex)
                        time.sleep(10)
        conn.request("GET", "/mcs/v2/devices/" + deviceId + "/datachannels/BB/datapoints", json.dumps(payload), headers)
        response = conn.getresponse()
        print( response.status, response.reason, json.dumps(payload), time.strftime("%c"))
        data = response.read()
        s = json.loads(data)
        print(s)
        a = s["dataChannels"]
        b = a[0]["dataPoints"][0]["values"]["value"]
        GPIO.output(17,b)
        conn.close()

# Try to grab a sensor reading.  Use the read_retry method which will retry up
# to 15 times to get a sensor reading (waiting 2 seconds between each retry).

while(True):
        payload = {}
        post_to_mcs(payload)
        time.sleep(1)                        
